version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    networks:
      - app-network
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
      - /tmp/zap:/tmp/zap 

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules

  zap:
    image: zaproxy/zap-stable
    networks:
      - app-network
  
  sonarqube:
    image: sonarqube
    networks:
      - sonarqube-network
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions

  sonar-scanner:
    image: sonarsource/sonar-scanner-cli
    networks:
      - sonarqube-network
   
networks:
  app-network:
    driver: bridge
  sonarqube-network:
    driver: bridge

volumes:
  sonarqube_data:
  sonarqube_extensions: