version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    networks:
      - app-network
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules

networks:
  app-network:
    driver: bridge