version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    depends_on:
      - zap
    networks:
      - zap-network
    restart: always

  zap:
    image: zaproxy/zap-stable:latest
    container_name: zap
    command: ["zap.sh", "-daemon", "-host", "0.0.0.0", "-port", "8090"]
    ports:
      - "8090:8090"
    networks:
      - zap-network
    volumes:
      - /zap/wrk:/zap/wrk
    restart: always

networks:
  zap-network:
    driver: bridge