import { useRef, useEffect, useState } from "react";
import { Button } from "@components/ui/button";
import { useReactToPrint } from "react-to-print";
import MiraLogo from "../../assets/MiraLogo.svg";
import useStore from "../../store/store"; 
import "../PDF/printtemplate.css";

export function ChatTemplate() {
  const templateRef = useRef<HTMLDivElement>(null);
  const [chatSummary, setChatSummary] = useState<string[]>([]); // Example chat messages
  const [selectedTemplate, setSelectedTemplate] = useState<string | null>(null);
  const [isPrinting, setIsPrinting] = useState(false);

  // Example user data
  const userData = useStore();
  const user = userData.user as any;

  useEffect(() => {
    
    // Fetch or generate chat summary
    setChatSummary([
      "1.Excecutive Summary:Another critical area that requires immediate attention is the absence of Content Security Policy (CSP) implementation.",
      "2. Technical Summary: The application is vulnerable to Cross-Site Scripting (XSS) attacks due to the absence of CSP headers.",
    ]);
  }, []);

  const handlePrint = useReactToPrint({
    contentRef: templateRef,
    documentTitle: selectedTemplate || "Template",
    onBeforePrint: () => {
      setIsPrinting(true);
      return Promise.resolve();
    },
    onAfterPrint: () => {
      setIsPrinting(false);
      setSelectedTemplate(null); // Reset after printing
    },
  });

  return (
    <div className="relative p-8">
      <div className="flex justify-between items-center absolute top-4 left-4 right-4">
        {/* Print Button */}
        <Button onClick={handlePrint} variant="outline">
          Print Chat Summary
        </Button>
      </div>

      <div ref={templateRef} className="mt-8 p-6 border border-gray-300 rounded-lg shadow-lg">
        {/* Header */}
        <div className="print-header">
          <div className="flex justify-between items-center">
            <div className="flex items-center">
              <img
                src={MiraLogo}
                alt="Mira Logo"
                className="h-12 w-12 rounded-full object-cover"
              />
            </div>
            <div className="text-center my-8">
                <h1 className="text-3xl font-bold">Chat Summary</h1>
            </div>
        <p className="text-sm text-right font-semibold">Generated by: {user?.username}</p>
        </div>
    </div>
 
        

        {/* Chat Summary Section */}
        <div className="mt-8 print-content">
          <h2 className="text-lg font-semibold mb-4">Conversation:</h2>
          <div>
            {chatSummary.map((message, index) => (
              <p key={index} className="mb-2 text-sm">{message}</p>
            ))}
          </div>
        </div>

        {/* Footer */}
        <div className="print-footer">
          <p>© 2025 denkMinds. All rights reserved.</p>
          
        </div>
      </div>
    </div>
  );
}
