import { mutation, query } from "./_generated/server";
import { v } from "convex/values";

// Save a Chat Message
export const saveChatMessage = mutation({
	args: {
		chatId: v.id("chats"), // ID of the chat
		sender: v.union(v.literal("user"), v.literal("ai")), // Sender type
		message: v.string(), // Message content
	},
	handler: async (ctx, { chatId, sender, message }) => {
		const now = Date.now();

		// Insert the chat message into the chatHistory table
		const result = await ctx.db.insert("chatHistory", {
			chatId,
			sender,
			message,
			createdAt: now,
		});

		// Update the `chats` table with the last updated timestamp
		await ctx.db.patch(chatId, { updatedAt: now });

		return result; // Return the inserted message ID
	},
});

// Get Chat History
export const getChatHistory = query({
	args: { chatId: v.id("chats") }, // ID of the chat
	handler: async (ctx, { chatId }) => {
		// Query the chatHistory table by chatId
		const chatHistory = await ctx.db
			.query("chatHistory")
			.withIndex("by_chatId", (q) => q.eq("chatId", chatId))
			.collect();

		return chatHistory; // Return the chat history
	},
});

// Save a Chat
export const saveChat = mutation({
	args: {
		userId: v.string(), // External userId (as string, not v.id)
		title: v.string(), // Title of the chat
	},
	handler: async (ctx, { userId, title }) => {
		const now = Date.now(); // Timestamp for creation

		// Insert a new chat entry into the chats table
		const chatId = await ctx.db.insert("chats", {
			userId, // Use the external userId string
			title,
			createdAt: now,
			updatedAt: now,
		});

		// Return the autogenerated chatId
		return chatId;
	},
});
